(() => {
  'use strict';
  const C = window.ABSEN_SUPABASE_CONFIG;
  let publicKey = '', token = '', session = null, masters = null;
  const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const rp = n => new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0);
  const alertMsg = (m,t='success') => window.showAlert ? window.showAlert(m,t) : alert(m);

  async function key(){
    if(publicKey) return publicKey;
    const r=await fetch(C.functionUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({function:'getPublicConfig',data:{}})});
    const j=await r.json(); publicKey=(j.result||j).anonKey||''; return publicKey;
  }
  function collect(v,out){if(typeof v==='string'&&v.length>20)out.push(v);else if(v&&typeof v==='object')Object.values(v).forEach(x=>collect(x,out))}
  function candidates(){const out=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i),v=localStorage.getItem(k)||'';/token|session/i.test(k||'')?out.unshift(v):out.push(v);try{collect(JSON.parse(v),out)}catch{}}return[...new Set(out)]}
  async function rpc(name,body){const k=await key();const r=await fetch(`${C.projectUrl}/rest/v1/rpc/${name}`,{method:'POST',headers:{'Content-Type':'application/json','apikey':k,'Authorization':`Bearer ${k}`},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw Error(j.message||j.error||'Permintaan gagal');return j}
  async function getSession(force=false){if(session&&!force)return session;for(const t of token?[token,...candidates()]:candidates()){try{const s=await rpc('payroll_api',{p_action:'session',p_token:t,p_payload:{}});token=t;session=s;return s}catch{}}throw Error('Sesi login belum ditemukan')}
  async function api(action,payload={}){await getSession();return rpc('payroll_api',{p_action:action,p_token:token,p_payload:payload})}

  function addStyle(){if(document.getElementById('feature-style'))return;const s=document.createElement('style');s.id='feature-style';s.textContent=`.fx-modal{position:fixed;inset:0;background:rgba(15,23,42,.7);z-index:12000;display:flex;align-items:center;justify-content:center;padding:16px}.fx-card{width:min(1120px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:18px}.fx-head{position:sticky;top:0;background:#fff;z-index:2;display:flex;justify-content:space-between;align-items:center;padding:18px 22px;border-bottom:1px solid #e2e8f0}.fx-body{padding:20px}.fx-close{border:0;background:#eef2ff;color:#4338ca;width:36px;height:36px;border-radius:50%;font-size:20px}.fx-table{width:100%;border-collapse:collapse;font-size:13px}.fx-table th,.fx-table td{padding:10px;border-bottom:1px solid #e2e8f0;text-align:left;vertical-align:top}.fx-table th{background:#f8fafc}.fx-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px}.fx-field{display:flex;flex-direction:column;gap:6px}.fx-field input,.fx-field select{padding:10px 12px;border:1px solid #cbd5e1;border-radius:10px}.fx-actions{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.fx-btn{border:0;border-radius:10px;padding:10px 14px;font-weight:700;background:#4f46e5;color:#fff;cursor:pointer}.fx-btn.alt{background:#e2e8f0;color:#0f172a}.fx-btn.danger{background:#dc2626}.fx-badge{display:inline-block;padding:3px 8px;border-radius:999px;background:#e0e7ff;color:#3730a3;font-size:11px;font-weight:800}.fx-empty{text-align:center;padding:30px;color:#64748b}.fx-menu{display:flex!important;align-items:center;width:100%;padding:.65rem .75rem;border:0;background:transparent;color:inherit;cursor:pointer;text-align:left;border-radius:8px}.fx-menu:hover{background:#f1f5f9}@media(max-width:700px){.fx-modal{padding:0}.fx-card{height:100vh;max-height:100vh;border-radius:0}.fx-body{padding:12px}.fx-table{font-size:12px}}`;document.head.appendChild(s)}
  function modal(title,html){addStyle();document.getElementById('fx-modal')?.remove();const m=document.createElement('div');m.id='fx-modal';m.className='fx-modal';m.innerHTML=`<div class="fx-card"><div class="fx-head"><h2>${esc(title)}</h2><button class="fx-close">×</button></div><div class="fx-body">${html}</div></div>`;m.querySelector('.fx-close').onclick=()=>m.remove();m.onclick=e=>{if(e.target===m)m.remove()};document.body.appendChild(m);return m}
  function printSlip(s,u){const w=open('','_blank');if(!w)return alertMsg('Popup diblokir','error');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Slip Gaji</title><style>body{font-family:Arial;padding:36px;color:#172033}.h{border-bottom:3px solid #243b64}.b{border:1px solid #cbd5e1;border-radius:10px;padding:16px;margin-top:18px}.r{display:flex;justify-content:space-between;padding:7px 0;border-bottom:1px solid #eee}.t{font-size:20px;font-weight:800;border-top:2px solid #243b64}@media print{button{display:none}}</style></head><body><div class="h"><h1>SLIP GAJI</h1><p>${esc(s.Periode_Mulai)} s.d. ${esc(s.Periode_Akhir)}</p></div><div class="b"><p>Nama: <b>${esc(u.Nama_Lengkap||'-')}</b></p><p>Jabatan: ${esc(u.Jabatan_Divisi||'-')}</p><p>SPPG: ${esc(s.SPPG||u.SPPG||'-')}</p><p>Yayasan: ${esc(s.Yayasan||u.Yayasan||'-')}</p></div><div class="b"><div class="r"><span>Hari kerja</span><b>${s.Jumlah_Hari_Kerja||0}</b></div><div class="r"><span>Gaji harian</span><b>${rp(s.Gaji_Harian)}</b></div><div class="r"><span>Subtotal</span><b>${rp(s.Subtotal_Gaji)}</b></div><div class="r"><span>Lembur</span><b>${rp(s.Lembur_Nominal)}</b></div><div class="r"><span>Bonus</span><b>${rp(s.Bonus)}</b></div><div class="r"><span>Potongan</span><b>${rp(s.Potongan)}</b></div><div class="r t"><span>Total diterima</span><span>${rp(s.Total_Gaji_Diterima)}</span></div></div><p>Diterbitkan: ${s.Diterbitkan_At?new Date(s.Diterbitkan_At).toLocaleString('id-ID'):'Belum diterbitkan'}</p><button onclick="print()">Cetak / Simpan PDF</button></body></html>`);w.document.close()}

  async function myAbsensi(){const m=modal('My Absen','<div class="fx-empty">Memuat...</div>');try{const x=await api('myAbsensi'),rows=x.rows||[];m.querySelector('.fx-body').innerHTML=`<table class="fx-table"><thead><tr><th>Tanggal</th><th>Jenis</th><th>Waktu</th><th>SPPG</th><th>Yayasan</th><th>Status</th></tr></thead><tbody>${rows.map(a=>`<tr><td>${esc(a.Tanggal)}</td><td>${esc(a.Jenis_Absen)}</td><td>${a.Waktu_Timestamp?new Date(a.Waktu_Timestamp).toLocaleTimeString('id-ID'):'-'}</td><td>${esc(a.SPPG)}</td><td>${esc(a.Yayasan)}</td><td>${esc(a.Status_Validasi)}</td></tr>`).join('')}</tbody></table>${rows.length?'':'<div class="fx-empty">Belum ada absensi.</div>'}`}catch(e){m.querySelector('.fx-body').innerHTML=`<div class="fx-empty">${esc(e.message)}</div>`}}
  async function myPayroll(){const m=modal('My Payroll','<div class="fx-empty">Memuat...</div>');try{const x=await api('myPayroll'),rows=x.rows||[],u=x.user||{};m.querySelector('.fx-body').innerHTML=`<table class="fx-table"><thead><tr><th>Periode</th><th>Hari</th><th>Total</th><th>Diterbitkan</th><th></th></tr></thead><tbody>${rows.map((s,i)=>`<tr><td>${esc(s.Periode_Mulai)} – ${esc(s.Periode_Akhir)}</td><td>${s.Jumlah_Hari_Kerja||0}</td><td><b>${rp(s.Total_Gaji_Diterima)}</b></td><td>${s.Diterbitkan_At?new Date(s.Diterbitkan_At).toLocaleDateString('id-ID'):'-'}</td><td><button class="fx-btn alt" data-p="${i}">Cetak</button></td></tr>`).join('')}</tbody></table>${rows.length?'':'<div class="fx-empty">Belum ada slip terbit.</div>'}`;m.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>printSlip(rows[+b.dataset.p],u))}catch(e){m.querySelector('.fx-body').innerHTML=`<div class="fx-empty">${esc(e.message)}</div>`}}
  async function payroll(){const m=modal('Payroll & Penerbitan Slip','<div class="fx-empty">Memuat...</div>');try{const x=await api('slips'),rows=x.rows||[],users=x.users||[],map=new Map(users.map(u=>[u.ID_User,u]));m.querySelector('.fx-body').innerHTML=`<div class="fx-actions"><button id="fx-publish" class="fx-btn">Terbitkan Terpilih</button><button id="fx-all" class="fx-btn alt">Pilih Semua</button></div><table class="fx-table"><thead><tr><th></th><th>Karyawan</th><th>SPPG / Yayasan</th><th>Periode</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>${rows.map((s,i)=>{const u=map.get(s.ID_User)||{};return`<tr><td><input type="checkbox" class="fx-slip" value="${esc(s.ID_Slip)}"></td><td><b>${esc(u.Nama_Lengkap||s.ID_User)}</b><br>${esc(u.Jabatan_Divisi||'')}</td><td>${esc(s.SPPG||u.SPPG||'-')}<br>${esc(s.Yayasan||u.Yayasan||'-')}</td><td>${esc(s.Periode_Mulai)} – ${esc(s.Periode_Akhir)}</td><td><b>${rp(s.Total_Gaji_Diterima)}</b></td><td><span class="fx-badge">${esc(s.Status_Penerbitan||'DRAFT')}</span></td><td><button class="fx-btn alt" data-p="${i}">Cetak</button></td></tr>`}).join('')}</tbody></table>${rows.length?'':'<div class="fx-empty">Belum ada payroll. Proses payroll lebih dulu, lalu terbitkan slip di sini.</div>'}`;m.querySelector('#fx-all').onclick=()=>m.querySelectorAll('.fx-slip').forEach(c=>c.checked=true);m.querySelector('#fx-publish').onclick=async()=>{const ids=[...m.querySelectorAll('.fx-slip:checked')].map(c=>c.value);try{await api('publish',{ids});alertMsg(`${ids.length} slip diterbitkan`);m.remove();payroll()}catch(e){alertMsg(e.message,'error')}};m.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{const s=rows[+b.dataset.p];printSlip(s,map.get(s.ID_User)||{})})}catch(e){m.querySelector('.fx-body').innerHTML=`<div class="fx-empty">${esc(e.message)}</div>`}}
  async function config(){const m=modal('Konfigurasi Admin','<div class="fx-empty">Memuat...</div>');try{const [x,all]=await Promise.all([api('config'),rpc('super_admin_users',{p_token:token})]),admins=x.admins||[],users=all.rows||[];m.querySelector('.fx-body').innerHTML=`<h3>Akses Data ADMIN / AKUNTAN</h3><div class="fx-grid"><div class="fx-field"><label>Akun</label><select id="fx-user">${admins.filter(a=>['ADMIN','AKUNTAN'].includes(String(a.Role).toUpperCase())).map(a=>`<option value="${esc(a.ID_User)}">${esc(a.Email)} — ${esc(a.Role)}</option>`).join('')}</select></div><div class="fx-field"><label>SPPG</label><input id="fx-sppg" list="fx-sppg-list"><datalist id="fx-sppg-list">${(x.sppg||[]).map(v=>`<option value="${esc(v)}">`).join('')}</datalist></div><div class="fx-field"><label>Yayasan</label><input id="fx-yayasan" list="fx-yayasan-list"><datalist id="fx-yayasan-list">${(x.yayasan||[]).map(v=>`<option value="${esc(v)}">`).join('')}</datalist></div></div><div class="fx-actions"><button id="fx-save" class="fx-btn">Simpan Akses</button></div><table class="fx-table"><thead><tr><th>Email</th><th>SPPG</th><th>Yayasan</th><th></th></tr></thead><tbody>${(x.access||[]).map(a=>`<tr><td>${esc(a.Email_Admin)}</td><td>${esc(a.SPPG)}</td><td>${esc(a.Yayasan)}</td><td><button class="fx-btn danger" data-d="${esc(a.ID_Access)}">Hapus</button></td></tr>`).join('')}</tbody></table><h3 style="margin-top:28px">Role Akun</h3><table class="fx-table"><thead><tr><th>Nama</th><th>Email</th><th>SPPG</th><th>Yayasan</th><th>Role</th></tr></thead><tbody>${users.map(u=>`<tr><td>${esc(u.Nama_Lengkap)}</td><td>${esc(u.Email)}</td><td>${esc(u.SPPG)}</td><td>${esc(u.Yayasan)}</td><td><select data-r="${esc(u.ID_User)}" ${String(u.Role).toUpperCase()==='SUPER ADMIN'?'disabled':''}><option ${u.Role==='USER'?'selected':''}>USER</option><option ${u.Role==='ADMIN'?'selected':''}>ADMIN</option><option ${u.Role==='AKUNTAN'?'selected':''}>AKUNTAN</option>${String(u.Role).toUpperCase()==='SUPER ADMIN'?'<option selected>SUPER ADMIN</option>':''}</select></td></tr>`).join('')}</tbody></table>`;m.querySelector('#fx-save').onclick=async()=>{try{await api('saveAccess',{idUser:m.querySelector('#fx-user').value,sppg:m.querySelector('#fx-sppg').value,yayasan:m.querySelector('#fx-yayasan').value});alertMsg('Akses disimpan');m.remove();config()}catch(e){alertMsg(e.message,'error')}};m.querySelectorAll('[data-d]').forEach(b=>b.onclick=async()=>{await api('deleteAccess',{id:b.dataset.d});m.remove();config()});m.querySelectorAll('[data-r]').forEach(s=>s.onchange=async()=>{try{await api('setRole',{idUser:s.dataset.r,role:s.value});alertMsg('Role diperbarui')}catch(e){alertMsg(e.message,'error')}})}catch(e){m.querySelector('.fx-body').innerHTML=`<div class="fx-empty">${esc(e.message)}</div>`}}

  async function injectRegistration(){const sppg=[...document.querySelectorAll('input,select')].find(e=>/sppg/i.test(`${e.id} ${e.name}`));if(!sppg||document.getElementById('reg-yayasan'))return;const g=document.createElement('div');g.className=sppg.closest('.form-group')?.className||'form-group';g.innerHTML='<label class="form-label">Yayasan <span style="color:#dc2626">*</span></label><input id="reg-yayasan" name="yayasan" class="form-input" list="reg-yayasan-list" required placeholder="Pilih atau ketik nama yayasan"><datalist id="reg-yayasan-list"></datalist>';(sppg.closest('.form-group')||sppg.parentElement).after(g);try{if(!masters)masters=await rpc('registration_options',{});g.querySelector('datalist').innerHTML=(masters.yayasan||[]).map(v=>`<option value="${esc(v)}">`).join('');if(sppg.tagName==='INPUT'){let d=document.getElementById('reg-sppg-list');if(!d){d=document.createElement('datalist');d.id='reg-sppg-list';document.body.appendChild(d)}d.innerHTML=(masters.sppg||[]).map(v=>`<option value="${esc(v)}">`).join('');sppg.setAttribute('list',d.id)}}catch{}}

  const originalFetch=window.fetch.bind(window);
  window.fetch=async function(input,init={}){let reg=null;try{const b=init.body&&JSON.parse(init.body);if(b?.function==='registerUser'){const y=document.getElementById('reg-yayasan')?.value.trim(),s=b.data?.sppg==='LAINNYA'?b.data.sppgLainnya:b.data?.sppg;if(!y)return new Response(JSON.stringify({success:false,error:'Yayasan wajib diisi'}),{headers:{'Content-Type':'application/json'}});reg={y,s,e:b.data.email};init={...init,body:JSON.stringify(b)}}}catch{}const res=await originalFetch(input,init);if(reg)try{const j=await res.clone().json(),v=j.result||j;if(j.success&&v.idUser){const k=await key();await originalFetch(`${C.projectUrl}/rest/v1/rpc/complete_registration_yayasan`,{method:'POST',headers:{'Content-Type':'application/json','apikey':k,'Authorization':`Bearer ${k}`},body:JSON.stringify({p_id_user:v.idUser,p_email:reg.e,p_sppg:reg.s,p_yayasan:reg.y})})}}catch(e){console.error(e)}return res};

  function add(parent,id,label,fn){if(!parent||document.getElementById(id))return;const b=document.createElement('button');b.id=id;b.className='fx-menu';b.type='button';b.textContent=label;b.onclick=e=>{e.preventDefault();e.stopPropagation();fn()};parent.appendChild(b)}
  async function enhance(){injectRegistration();try{const s=await getSession(),role=s.user.role,drop=document.querySelector('.app-topbar-dropdown'),nav=document.querySelector('.app-nav');add(drop,'fx-myabsen','My Absen',myAbsensi);add(drop,'fx-mypayroll','My Payroll',myPayroll);if(['SUPER ADMIN','ADMIN','AKUNTAN'].includes(role))add(nav,'fx-payroll','Payroll',payroll);if(role==='SUPER ADMIN')add(nav,'fx-config','Konfigurasi Admin',config)}catch{}}
  document.addEventListener('DOMContentLoaded',()=>{addStyle();enhance();setInterval(enhance,1500)});
})();