import { createClient } from "jsr:@supabase/supabase-js@2";
import { corsHeaders, jsonResponse, requestId } from "../_shared/http.ts";

const url=Deno.env.get('SUPABASE_URL')!; const key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const db=createClient(url,key,{auth:{persistSession:false}});
const operatorRoles=new Set(['ADMIN','SUPER ADMIN','AKUNTAN']);
const roleOf=(v:unknown)=>String(v||'').toUpperCase().replace(/_/g,' ');
async function auth(token:unknown){const t=String(token||'').trim();if(!t)throw new Error('SESSION_EXPIRED');const s=await db.from('Sessions').select('ID_User,Type,Expires_At').eq('Token',t).maybeSingle();if(s.error||!s.data?.ID_User||new Date(s.data.Expires_At).getTime()<=Date.now())throw new Error('SESSION_EXPIRED');const u=await db.from('Users').select('ID_User,Role,Status_Aktif').eq('ID_User',s.data.ID_User).maybeSingle();if(u.error||!u.data||u.data.Status_Aktif===false)throw new Error('ACCOUNT_INACTIVE');return{id:String(u.data.ID_User),role:roleOf(u.data.Role)};}
Deno.serve(async req=>{const id=requestId();const headers=corsHeaders(req);if(req.method==='OPTIONS')return new Response(null,{status:204,headers});if(req.method!=='POST')return jsonResponse({success:false,code:'METHOD_NOT_ALLOWED',message:'Gunakan POST.',requestId:id},405,headers);try{const body=await req.json();const actor=await auth(body.token);const action=String(body.action||'');if(action==='create'){const reason=String(body.reason||'').trim();if(reason.length<10) return jsonResponse({success:false,code:'VALIDATION_ERROR',message:'Alasan minimal 10 karakter.',requestId:id},422,headers);const row={ID_User:actor.id,ID_Absensi:body.attendanceId||null,Attendance_Date:body.attendanceDate,Correction_Type:body.correctionType,Requested_Values:body.requestedValues||{},Reason:reason,Evidence_URL:body.evidenceUrl||null};const r=await db.from('Attendance_Corrections').insert(row).select('*').single();if(r.error)throw r.error;return jsonResponse({success:true,result:r.data,requestId:id},201,headers);}if(action==='listMine'){const r=await db.from('Attendance_Corrections').select('*').eq('ID_User',actor.id).order('Submitted_At',{ascending:false}).limit(100);if(r.error)throw r.error;return jsonResponse({success:true,result:r.data,requestId:id},200,headers);}if(action==='listQueue'){if(!operatorRoles.has(actor.role))return jsonResponse({success:false,code:'FORBIDDEN',message:'Akses ditolak.',requestId:id},403,headers);let q=db.from('Attendance_Corrections').select('*').order('Submitted_At',{ascending:false}).limit(100);if(body.status)q=q.eq('Status',String(body.status));const r=await q;if(r.error)throw r.error;return jsonResponse({success:true,result:r.data,requestId:id},200,headers);}if(action==='review'){if(!operatorRoles.has(actor.role))return jsonResponse({success:false,code:'FORBIDDEN',message:'Akses ditolak.',requestId:id},403,headers);const status=String(body.status||'').toUpperCase();const notes=String(body.notes||'').trim();if(!['APPROVED','REJECTED'].includes(status)||notes.length<10)return jsonResponse({success:false,code:'VALIDATION_ERROR',message:'Status dan catatan review minimal 10 karakter wajib diisi.',requestId:id},422,headers);const r=await db.rpc('apply_attendance_correction',{p_correction_id:body.correctionId,p_reviewer_id:actor.id,p_status:status,p_notes:notes});if(r.error)throw r.error;return jsonResponse({success:true,result:r.data,requestId:id},200,headers);}return jsonResponse({success:false,code:'ACTION_NOT_FOUND',message:'Aksi tidak tersedia.',requestId:id},404,headers);}catch(e){console.error(JSON.stringify({requestId:id,error:String(e)}));return jsonResponse({success:false,code:'INTERNAL_ERROR',message:'Layanan koreksi presensi gagal memproses permintaan.',requestId:id},500,headers);}});
