import {createClient} from 'jsr:@supabase/supabase-js@2';
import {corsHeaders,createRequestId,jsonResponse} from '../_shared/http.ts';
const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});
const corsOptions={allowedOriginsEnv:Deno.env.get('ABSEN_ALLOWED_ORIGINS')||'',productionOrigin:'https://absen-sppg.pages.dev',previewSuffix:'.absen-sppg.pages.dev',localOrigins:['http://localhost:4173','http://127.0.0.1:4173']};
async function auth(token:string){const s=await db.from('Sessions').select('ID_User,Expires_At').eq('Token',token).maybeSingle();if(s.error||!s.data||new Date(s.data.Expires_At).getTime()<=Date.now())throw new Error('SESSION_EXPIRED');const u=await db.from('Users').select('ID_User,Role').eq('ID_User',s.data.ID_User).maybeSingle();if(u.error||!u.data)throw new Error('FORBIDDEN');return{id:String(u.data.ID_User),role:String(u.data.Role||'').replaceAll('_',' ').toUpperCase()};}
Deno.serve(async req=>{const origin=req.headers.get('origin');const headers=corsHeaders(origin,corsOptions);if(req.method==='OPTIONS')return new Response(null,{status:204,headers});const id=createRequestId();try{const body=await req.json();const actor=await auth(String(body.token||''));const op=String(body.action||'');if(op==='readiness'){const r=await db.rpc('platform_readiness_summary');if(r.error)throw r.error;return jsonResponse({success:true,result:r.data,requestId:id},200,headers);}
if(op==='privacyRequest'){const r=await db.from('Privacy_Requests').insert({ID_User:actor.id,Request_Type:String(body.type||''),Reason:String(body.reason||'').slice(0,2000)}).select().single();if(r.error)throw r.error;return jsonResponse({success:true,result:r.data,requestId:id},201,headers);}
if(!['ADMIN','SUPER ADMIN','AKUNTAN'].includes(actor.role))throw new Error('FORBIDDEN');if(op==='retentionPolicies'){const r=await db.from('Data_Retention_Policies').select('*').order('Data_Type');if(r.error)throw r.error;return jsonResponse({success:true,result:r.data,requestId:id},200,headers);}
if(op==='purgePreview'){const r=await db.rpc('purge_expired_operational_data',{p_dry_run:true});if(r.error)throw r.error;return jsonResponse({success:true,result:r.data,requestId:id},200,headers);}
throw new Error('UNKNOWN_ACTION');}catch(e){const m=String((e as Error).message||e);const status=m==='SESSION_EXPIRED'?401:m==='FORBIDDEN'?403:422;return jsonResponse({success:false,code:m,message:m,requestId:id},status,headers);}});