import { createClient } from "jsr:@supabase/supabase-js@2";
import { corsHeaders, createRequestId, isOriginAllowed, jsonResponse } from "../_shared/http.ts";
import { optionalString, requiredString, ValidationError } from "../_shared/validation.ts";
import { normalizeRole, OPERATIONAL_ROLES } from "../_shared/contracts.ts";

const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});
const corsOptions={allowedOriginsEnv:Deno.env.get('ABSEN_ALLOWED_ORIGINS')||'',productionOrigin:'https://absen-sppg.pages.dev',previewSuffix:'.absen-sppg.pages.dev',localOrigins:['http://localhost:4173','http://127.0.0.1:4173']};
type Auth={idUser:string;role:string};
async function auth(tokenValue:unknown):Promise<Auth>{const token=requiredString(tokenValue,'token',{min:16,max:512});const s=await db.from('Sessions').select('ID_User,Type,Expires_At').eq('Token',token).maybeSingle();if(s.error||!s.data?.ID_User||String(s.data.Type).toLowerCase()!=='user'||new Date(s.data.Expires_At).getTime()<=Date.now())throw new Error('SESSION_EXPIRED');const u=await db.from('Users').select('ID_User,Role,Status_Aktif').eq('ID_User',s.data.ID_User).maybeSingle();if(u.error||!u.data)throw new Error('ACCOUNT_INACTIVE');return{idUser:String(u.data.ID_User),role:normalizeRole(u.data.Role)};}
const requireOps=(a:Auth)=>{if(!OPERATIONAL_ROLES.includes(a.role as typeof OPERATIONAL_ROLES[number]))throw new Error('FORBIDDEN');};
async function listNotifications(a:Auth,b:Record<string,unknown>){const limit=Math.min(100,Math.max(1,Number(b.limit||30)));let q=db.from('Notifications').select('*').or(`ID_User.eq.${a.idUser},Target_Role.eq.${a.role}`).order('Created_At',{ascending:false}).limit(limit);if(b.unreadOnly)q=q.is('Read_At',null);const r=await q;if(r.error)throw new Error('NOTIFICATION_QUERY_FAILED');return r.data||[];}
async function markRead(a:Auth,b:Record<string,unknown>){const id=requiredString(b.notificationId,'notificationId',{max:100});const r=await db.rpc('mark_notification_read',{p_notification_id:id,p_user_id:a.idUser});if(r.error||!r.data)throw new Error('NOTIFICATION_NOT_FOUND');return{updated:true};}
async function preferences(a:Auth,b:Record<string,unknown>){if(b.save){const row={ID_User:a.idUser,In_App_Enabled:b.inAppEnabled!==false,Push_Enabled:b.pushEnabled!==false,Sound_Enabled:b.soundEnabled===true,Quiet_Hours_Start:b.quietHoursStart||null,Quiet_Hours_End:b.quietHoursEnd||null,Updated_At:new Date().toISOString()};const r=await db.from('Notification_Preferences').upsert(row).select().single();if(r.error)throw new Error('PREFERENCE_SAVE_FAILED');return r.data;}const r=await db.from('Notification_Preferences').select('*').eq('ID_User',a.idUser).maybeSingle();if(r.error)throw new Error('PREFERENCE_QUERY_FAILED');return r.data||{ID_User:a.idUser,In_App_Enabled:true,Push_Enabled:true,Sound_Enabled:false};}
async function assignShift(a:Auth,b:Record<string,unknown>){requireOps(a);const row={ID_User:requiredString(b.userId,'userId',{max:100}),Shift_ID:requiredString(b.shiftId,'shiftId',{max:100}),SPPG:optionalString(b.sppg,200),Valid_From:requiredString(b.validFrom,'validFrom',{max:10}),Valid_Until:optionalString(b.validUntil,10),Assigned_By:a.idUser,Notes:optionalString(b.notes,1000),Is_Active:true};const r=await db.from('Work_Shift_Assignments').insert(row).select().single();if(r.error)throw new Error('SHIFT_ASSIGN_FAILED');return r.data;}
async function listShiftAssignments(a:Auth,b:Record<string,unknown>){requireOps(a);let q=db.from('Work_Shift_Assignments').select('*').order('Valid_From',{ascending:false}).limit(200);if(b.userId)q=q.eq('ID_User',String(b.userId));if(b.sppg)q=q.eq('SPPG',String(b.sppg));const r=await q;if(r.error)throw new Error('SHIFT_QUERY_FAILED');return r.data||[];}
async function analytics(a:Auth,b:Record<string,unknown>){requireOps(a);const from=requiredString(b.from,'from',{max:10});const to=requiredString(b.to,'to',{max:10});const r=await db.rpc('attendance_analytics_summary',{p_from:from,p_to:to,p_sppg:b.sppg?String(b.sppg):null});if(r.error)throw new Error('ANALYTICS_QUERY_FAILED');return r.data;}
async function scheduleReport(a:Auth,b:Record<string,unknown>){requireOps(a);const row={Name:requiredString(b.name,'name',{min:3,max:200}),Report_Type:requiredString(b.reportType,'reportType',{max:30}).toUpperCase(),SPPG:optionalString(b.sppg,200),Frequency:requiredString(b.frequency,'frequency',{max:20}).toUpperCase(),Format:String(b.format||'CSV').toUpperCase(),Recipients:Array.isArray(b.recipients)?b.recipients:[],Filters:b.filters||{},Next_Run_At:b.nextRunAt||null,Created_By:a.idUser};const r=await db.from('Report_Schedules').insert(row).select().single();if(r.error)throw new Error('REPORT_SCHEDULE_FAILED');return r.data;}
Deno.serve(async req=>{const id=createRequestId();const origin=req.headers.get('origin');const headers=corsHeaders(origin,corsOptions);if(req.method==='OPTIONS')return new Response(null,{status:isOriginAllowed(origin,corsOptions)?204:403,headers});try{const body=await req.json();const a=await auth(body.token);const action=String(body.action||'');let result;switch(action){case'listNotifications':result=await listNotifications(a,body);break;case'markNotificationRead':result=await markRead(a,body);break;case'notificationPreferences':result=await preferences(a,body);break;case'assignShift':result=await assignShift(a,body);break;case'listShiftAssignments':result=await listShiftAssignments(a,body);break;case'analyticsSummary':result=await analytics(a,body);break;case'scheduleReport':result=await scheduleReport(a,body);break;default:throw new ValidationError('Action tidak valid.','action');}return jsonResponse({success:true,result,requestId:id},200,id,headers);}catch(error){const m=error instanceof Error?error.message:String(error);const status=m==='SESSION_EXPIRED'?401:m==='FORBIDDEN'?403:error instanceof ValidationError?422:500;return jsonResponse({success:false,code:m,message:status===500?'Terjadi kesalahan pada server.':m,requestId:id},status,id,headers);}});
