const CANONICAL_ORIGIN = 'https://hadirly.org';
const LEGACY_HOSTS = new Set(['absen-sppg.pages.dev']);
if (LEGACY_HOSTS.has(window.location.hostname.toLowerCase())) {
  const target = new URL(window.location.pathname + window.location.search + window.location.hash, CANONICAL_ORIGIN);
  window.location.replace(target.href);
  throw new Error('Redirecting to canonical domain');
}

import { createRouter } from './router.js';
import { createAppStore } from '../stores/app-store.js';
import { createFeatureRegistry } from './feature-registry.js';
import { renderAttendanceProgress, showAttendanceReceipt, renderCorrectionWorkspace, openCorrectionForm } from '../pages/attendance/attendance-experience.js';
import { renderReleaseOperationsPage } from '../pages/release/release-operations-page.js';
import { renderWorkforceOperationsPage } from '../pages/workforce/workforce-operations-page.js';
import { renderPlatformOperationsPage } from '../pages/platform/platform-operations-page.js';

const VERSION = '26.11.45';
const loadedAssets = new Map();
function canonicalPath(value) { return new URL(value, document.baseURI).pathname; }
function loadStyle(path) { const key=`style:${canonicalPath(path)}`; if(loadedAssets.has(key))return loadedAssets.get(key); const existing=[...document.querySelectorAll('link[rel="stylesheet"][href]')].find((node)=>canonicalPath(node.href)===canonicalPath(path)); if(existing){const ready=Promise.resolve(existing);loadedAssets.set(key,ready);return ready;} const ready=new Promise((resolve,reject)=>{const link=document.createElement('link');link.rel='stylesheet';link.href=path;link.onload=()=>resolve(link);link.onerror=()=>reject(new Error(`Gagal memuat stylesheet: ${path}`));document.head.appendChild(link);});loadedAssets.set(key,ready);return ready; }
function loadScript(path) { const key=`script:${canonicalPath(path)}`; if(loadedAssets.has(key))return loadedAssets.get(key); const existing=[...document.querySelectorAll('script[src]')].find((node)=>canonicalPath(node.src)===canonicalPath(path)); if(existing){const ready=Promise.resolve(existing);loadedAssets.set(key,ready);return ready;} const ready=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=path;script.defer=true;script.onload=()=>resolve(script);script.onerror=()=>reject(new Error(`Gagal memuat script: ${path}`));document.head.appendChild(script);});loadedAssets.set(key,ready);return ready; }

export async function bootstrapApp() {
  if (window.AbsenApp) return window.AbsenApp;
  await Promise.all([
    './src/styles/foundation/tokens.css','./src/styles/foundation/reset.css','./src/styles/app-system.css','./src/styles/feature-pages.css','./src/styles/device-trust-policy.css','./src/styles/attendance-experience.css','./src/styles/attendance-import.css','./src/styles/config-center.css','./src/styles/payroll-history.css','./src/styles/app-announcements.css','./src/styles/notification-mobile.css','./src/styles/components/operational-notifications.css','./security-operations-ui.css','./src/styles/responsive-overrides.css','./src/styles/mobile-ui-refresh.css','./src/styles/foundation/components.css','./src/styles/foundation/motion-accessibility.css','./src/styles/components/in-app-confirm.css','./src/styles/layout/app-shell.css','./src/styles/pages/dashboard-bento.css','./src/styles/components/toolbar-system.css','./src/styles/components/responsive-tables.css','./src/styles/pages/payroll-refresh.css','./src/styles/pages/profile-forms-modals.css','./src/styles/pages/digital-id-card.css','./src/styles/pages/id-card-front-signature.css','./src/styles/pages/digital-id-card-master-renderer.css','./src/styles/pages/employment-contracts.css','./src/styles/pages/employment-contract-navigation.css','./src/styles/pages/complaints-activity.css','./src/styles/pages/settings-user-management.css','./src/styles/pages/super-admin-settings-hub.css','./src/styles/pages/system-settings-controller.css','./src/styles/pages/notification-publisher.css','./src/styles/foundation/quality-accessibility.css','./src/styles/pages/dashboard-mobile-polish.css','./src/styles/pages/super-admin-dashboard.css','./src/styles/pages/super-dashboard-polish.css','./src/styles/branding/hadirly.css'
  ].map((path)=>loadStyle(`${path}?v=${VERSION}`)));
  const store=createAppStore({route:window.location.hash.replace(/^#\/?/,'')||'dashboard'}); const router=createRouter({onRoute:(route)=>store.setState({route})}); const features=createFeatureRegistry();
  const attendanceExperience=Object.freeze({renderProgress:renderAttendanceProgress,showReceipt:showAttendanceReceipt,renderCorrections:renderCorrectionWorkspace,openCorrectionForm}); const releaseOperations=Object.freeze({render:renderReleaseOperationsPage}); const workforceOperations=Object.freeze({render:renderWorkforceOperationsPage}); const platformOperations=Object.freeze({render:renderPlatformOperationsPage});
  const app=Object.freeze({store,router,features,attendanceExperience,releaseOperations,workforceOperations,platformOperations,version:VERSION}); Object.assign(window,{AbsenApp:app,AbsenFeatures:features,AttendanceExperience:attendanceExperience,ReleaseOperations:releaseOperations,WorkforceOperations:workforceOperations,PlatformOperations:platformOperations});
  const scripts=['./src/app/hadirly-branding.js','./src/app/remove-legacy-notifications.js','./src/app/attendance-location-flow.js','./pwa-runtime.js','./src/app/layout-enhancements.js','./src/app/mobile-ui-refresh.js','./src/app/dashboard-bento.js','./src/app/dashboard-priority.js','./src/app/super-admin-dashboard.js','./src/app/toolbar-system.js','./src/app/responsive-tables.js','./src/app/payroll-refresh.js','./src/app/profile-forms-modals.js','./src/app/profile-employment-editor.js','./src/app/profile-contract-identity.js','./src/app/id-card-profile-action-policy.js','./src/app/digital-id-card.js','./src/app/id-card-front-signature-renderer.js','./src/app/digital-id-card-master-renderer.js','./src/app/employment-contracts.js','./src/app/employment-contract-navigation.js','./src/app/complaints-activity.js','./src/app/settings-user-management.js','./src/app/quality-accessibility.js','./security-ops-client.js','./security-operations-ui.js','./src/app/in-app-confirm.js','./src/app/super-admin-settings-hub.js','./src/app/system-settings.js','./src/app/attendance-import.js','./src/app/attendance-import-search-fix.js','./src/app/config-center.js','./src/app/notification-publisher.js','./src/app/operational-notifications.js','./src/features/payroll/payroll-history.js','./src/features/notifications/app-announcements.js','./src/features/sppg-location-config.js'];
  for(const path of scripts) await loadScript(`${path}?v=${VERSION}`); window.dispatchEvent(new CustomEvent('absen:app-ready',{detail:{version:VERSION,features:features.names()}})); return app;
}
bootstrapApp().catch((error)=>{if(error?.message!=='Redirecting to canonical domain')console.warn('Frontend modular gagal dimuat; aplikasi utama tetap aktif.',error);});
