(() => {
  const endpoint = `${window.ABSEN_SUPABASE_CONFIG.projectUrl}/functions/v1/ConfigCenter`;
  const state = { admin: null, notifications: [], lastShown: new Set() };
  const token = () => localStorage.getItem('auth_token');
  const user = () => { try { return JSON.parse(localStorage.getItem('auth_user') || 'null'); } catch { return null; } };
  const role = () => String(user()?.role || user()?.Role || '').toUpperCase().replace(/_/g, ' ').trim();
  const esc = (v) => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function call(action, payload={}) { const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,token:token(),...payload})}); const b=await r.json().catch(()=>({})); if(!r.ok||b.success===false) throw new Error(b.message||'Proses gagal.'); return b.result; }

  function ensureAdminMenu(){ document.querySelectorAll('[data-config-center-menu]').forEach(n=>n.remove()); if(role()!=='SUPER ADMIN'||!token())return; const nav=document.querySelector('.app-nav'); if(nav){const b=document.createElement('button');b.type='button';b.className='app-nav-item';b.dataset.configCenterMenu='desktop';b.innerHTML='<span>⚙️</span><span>Konfigurasi Absensi & Notifikasi</span>';b.onclick=openAdmin;nav.appendChild(b);} const mobile=document.querySelector('#mobile-more-menu'); if(mobile){const b=document.createElement('button');b.type='button';b.className='mobile-more-menu-item';b.dataset.configCenterMenu='mobile';b.textContent='⚙️ Konfigurasi Absensi & Notifikasi';b.onclick=()=>{mobile.classList.remove('active');openAdmin();};mobile.appendChild(b);} }

  function faceTab(){const sppg=state.admin?.sppg||[];return `<div class="cc-grid"><section class="cc-card"><h3>Aturan per SPPG</h3><p>Pilih satu atau beberapa SPPG lalu aktifkan/nonaktifkan scan wajah.</p><div class="cc-list">${sppg.map(s=>`<label><input type="checkbox" data-cc-sppg value="${esc(s.Nama_SPPG)}"> ${esc(s.Nama_SPPG)}</label>`).join('')}</div><div class="cc-actions"><button data-cc-sppg-on>Aktifkan</button><button data-cc-sppg-off>Nonaktifkan</button></div></section><section class="cc-card"><h3>Aturan per Karyawan</h3><select id="cc-user-sppg"><option value="">Pilih SPPG</option>${sppg.map(s=>`<option>${esc(s.Nama_SPPG)}</option>`).join('')}</select><div class="cc-actions"><button data-cc-select-all>Pilih semua</button><button data-cc-clear-all>Hapus pilihan</button></div><div id="cc-user-list" class="cc-list"><em>Pilih SPPG untuk melihat karyawan.</em></div><div class="cc-actions"><button data-cc-user-on>Aktifkan</button><button data-cc-user-off>Nonaktifkan</button></div></section></div>`;}
  function notifTab(){const sppg=state.admin?.sppg||[];return `<section class="cc-card"><h3>Buat Notifikasi</h3><div class="cc-form"><label>Judul<input id="cc-title" maxlength="120"></label><label>Isi<textarea id="cc-message" rows="4" maxlength="1000"></textarea></label><label>Prioritas<select id="cc-priority"><option>NORMAL</option><option>TINGGI</option><option>MENDESAK</option><option>RENDAH</option></select></label><label>Target<select id="cc-target-mode"><option value="ALL">Semua akun</option><option value="ROLES">Role tertentu</option><option value="SPPG">SPPG tertentu</option><option value="USERS">Karyawan tertentu</option></select></label><div id="cc-target-detail"></div><label><input type="checkbox" id="cc-banner" checked> Tampilkan banner dashboard</label><label><input type="checkbox" id="cc-sound" checked> Bunyi notifikasi</label><label><input type="checkbox" id="cc-push" checked> Push ke perangkat/PWA</label><button id="cc-publish">Publikasikan Notifikasi</button></div></section>`;}
  async function openAdmin(){try{state.admin=await call('adminConfig');}catch(e){window.showAlert?.(e.message,'error');return;}document.body.insertAdjacentHTML('beforeend',`<div class="cc-modal"><div class="cc-panel"><header><div><h2>Konfigurasi Absensi & Notifikasi</h2><p>Khusus SUPER ADMIN</p></div><button data-cc-close>✕</button></header><div class="cc-tabs"><button data-tab="face" class="active">Scan Wajah</button><button data-tab="notif">Notifikasi</button></div><div id="cc-body">${faceTab()}</div></div></div>`);bindAdmin();}
  function bindAdmin(){const modal=document.querySelector('.cc-modal');modal.querySelector('[data-cc-close]').onclick=()=>modal.remove();modal.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{modal.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));modal.querySelector('#cc-body').innerHTML=b.dataset.tab==='face'?faceTab():notifTab();b.dataset.tab==='face'?bindFace():bindNotif();});bindFace();}
  function selectedValues(sel){return [...document.querySelectorAll(sel+':checked')].map(x=>x.value||x.dataset.id);}
  async function saveFace(scope,enabled,extra){try{await call('saveFacePolicy',{scope,enabled,...extra});window.showAlert?.('Konfigurasi scan wajah tersimpan.','success');state.admin=await call('adminConfig');}catch(e){window.showAlert?.(e.message,'error');}}
  function bindFace(){document.querySelector('[data-cc-sppg-on]').onclick=()=>saveFace('SPPG',true,{sppg:selectedValues('[data-cc-sppg]')});document.querySelector('[data-cc-sppg-off]').onclick=()=>saveFace('SPPG',false,{sppg:selectedValues('[data-cc-sppg]')});const select=document.querySelector('#cc-user-sppg'),list=document.querySelector('#cc-user-list');select.onchange=()=>{const users=(state.admin.users||[]).filter(u=>u.SPPG===select.value);list.innerHTML=users.map(u=>`<label><input type="checkbox" data-cc-user data-id="${esc(u.ID_User)}"> <span>${esc(u.Nama_Lengkap)}<small>${esc(u.Jabatan_Divisi||'')}</small></span></label>`).join('')||'<em>Tidak ada karyawan aktif.</em>';};document.querySelector('[data-cc-select-all]').onclick=()=>list.querySelectorAll('[data-cc-user]').forEach(x=>x.checked=true);document.querySelector('[data-cc-clear-all]').onclick=()=>list.querySelectorAll('[data-cc-user]').forEach(x=>x.checked=false);document.querySelector('[data-cc-user-on]').onclick=()=>saveFace('USER',true,{userIds:selectedValues('[data-cc-user]')});document.querySelector('[data-cc-user-off]').onclick=()=>saveFace('USER',false,{userIds:selectedValues('[data-cc-user]')});}
  function bindNotif(){const mode=document.querySelector('#cc-target-mode'),detail=document.querySelector('#cc-target-detail');const render=()=>{if(mode.value==='ROLES')detail.innerHTML='<label><input type="checkbox" data-role value="USER"> USER</label><label><input type="checkbox" data-role value="ADMIN"> ADMIN</label><label><input type="checkbox" data-role value="AKUNTAN"> AKUNTAN</label>';else if(mode.value==='SPPG')detail.innerHTML=(state.admin.sppg||[]).map(s=>`<label><input type="checkbox" data-sppg-target value="${esc(s.Nama_SPPG)}"> ${esc(s.Nama_SPPG)}</label>`).join('');else if(mode.value==='USERS')detail.innerHTML=`<select id="cc-notif-sppg"><option value="">Pilih SPPG</option>${(state.admin.sppg||[]).map(s=>`<option>${esc(s.Nama_SPPG)}</option>`).join('')}</select><div id="cc-notif-users" class="cc-list"></div>`;else detail.innerHTML='';if(mode.value==='USERS'){document.querySelector('#cc-notif-sppg').onchange=e=>{document.querySelector('#cc-notif-users').innerHTML=(state.admin.users||[]).filter(u=>u.SPPG===e.target.value).map(u=>`<label><input type="checkbox" data-user-target data-id="${esc(u.ID_User)}"> ${esc(u.Nama_Lengkap)}</label>`).join('');};}};mode.onchange=render;render();document.querySelector('#cc-publish').onclick=async()=>{try{await call('publishNotification',{title:document.querySelector('#cc-title').value,message:document.querySelector('#cc-message').value,priority:document.querySelector('#cc-priority').value,targetMode:mode.value,targetRoles:selectedValues('[data-role]'),targetSppg:selectedValues('[data-sppg-target]'),targetUserIds:selectedValues('[data-user-target]'),showBanner:document.querySelector('#cc-banner').checked,playSound:document.querySelector('#cc-sound').checked,pushEnabled:document.querySelector('#cc-push').checked});window.showAlert?.('Notifikasi berhasil dipublikasikan.','success');document.querySelector('.cc-modal')?.remove();await loadNotifications(true);}catch(e){window.showAlert?.(e.message,'error');}};}

  function sound(){try{const a=new AudioContext();const o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.value=880;g.gain.setValueAtTime(.08,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.35);o.start();o.stop(a.currentTime+.35);}catch{}}
  function ensureBell(){let b=document.querySelector('[data-cc-bell]');if(b)return b;b=document.createElement('button');b.type='button';b.dataset.ccBell='';b.className='cc-bell';b.innerHTML='🔔<span>0</span>';b.onclick=showNotificationPanel;(document.querySelector('.topbar-actions')||document.body).appendChild(b);return b;}
  async function loadNotifications(force=false){if(!token())return;try{const r=await call('getNotifications');state.notifications=r.items||[];const bell=ensureBell();bell.querySelector('span').textContent=String(r.unread||0);const fresh=state.notifications.filter(n=>!n.Read&&!state.lastShown.has(n.ID_Notification));for(const n of fresh){state.lastShown.add(n.ID_Notification);if(n.Show_Banner)showBanner(n);if(n.Play_Sound)sound();if(n.Push_Enabled&&Notification.permission==='granted'&&(force||document.hidden)){navigator.serviceWorker?.ready.then(reg=>reg.showNotification(n.Title,{body:n.Message,icon:'./icon-192.png',badge:'./icon-192.png',data:{id:n.ID_Notification}})).catch(()=>{});}}}catch{}}
  function showBanner(n){document.querySelector('[data-cc-banner]')?.remove();const d=document.createElement('div');d.dataset.ccBanner='';d.className=`cc-banner ${String(n.Priority).toLowerCase()}`;d.innerHTML=`<div><strong>${esc(n.Title)}</strong><p>${esc(n.Message)}</p></div><button>✕</button>`;d.querySelector('button').onclick=()=>{call('markRead',{id:n.ID_Notification}).catch(()=>{});d.remove();loadNotifications();};(document.querySelector('.main-content')||document.body).prepend(d);}
  function showNotificationPanel(){document.querySelector('.cc-notification-panel')?.remove();const p=document.createElement('div');p.className='cc-notification-panel';p.innerHTML=`<header><strong>Notifikasi</strong><button>✕</button></header>${state.notifications.map(n=>`<article class="${n.Read?'read':''}" data-id="${n.ID_Notification}"><b>${esc(n.Title)}</b><p>${esc(n.Message)}</p><small>${new Date(n.Created_At).toLocaleString('id-ID')}</small></article>`).join('')||'<em>Belum ada notifikasi.</em>'}`;p.querySelector('header button').onclick=()=>p.remove();p.querySelectorAll('article').forEach(a=>a.onclick=async()=>{await call('markRead',{id:a.dataset.id});a.classList.add('read');loadNotifications();});document.body.appendChild(p);}
  async function checkFaceAvailability(){if(!token())return;try{const r=await call('getFaceStatus');window.FACE_ATTENDANCE_ENABLED=r.enabled;document.documentElement.dataset.faceAttendanceEnabled=String(r.enabled);if(!r.enabled)document.querySelectorAll('[data-view="absen"],#btn-absen,.btn-absen').forEach(x=>{x.setAttribute('aria-disabled','true');x.title='Scan wajah dinonaktifkan oleh SUPER ADMIN';});}catch{}}
  const sync=()=>{ensureAdminMenu();ensureBell();loadNotifications();checkFaceAvailability();};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',sync,{once:true});else sync();
  window.addEventListener('absen:app-ready',sync);window.addEventListener('absen:session-changed',sync);setInterval(loadNotifications,30000);setInterval(checkFaceAvailability,60000);
})();